### ISSUE TITLE
Directly creating a podio.Client object

### ISSUE THREAD

**Issue by pjmuller** [andreas/podio-go#10]
Hi Andreas,

I'm a very beginner in Golang and I am getting into problems for directly creating a Client object (without calling `AuthWithAuthCode`)

Could you quickly check my post on stackoverflow: http://stackoverflow.com/questions/38139640/how-to-directly-pass-podio-authtoken-to-podio-go-client

Thanks :) !

I'm planning to contribute quite a bit once I have everything up and running with some extra methods

**Comment by andreas** [comment]
Please see answer on StackOverflow :)

Looking forward to your contributions!
