### ISSUE TITLE
access raw Podio field values

### ISSUE THREAD

**Issue by pjmuller** [andreas/podio-go#13]
Hi Andreas,

it's me again, still trying to get deeper and deeper into golang (for the record, the updates on the pull requests are coming!).

Currently I'm trying to distill a very much simplified map for the item values. But I can't seem to dig deeper into the `podio.Field.Values` struct.

Also on stackoverflow others were not able to help me yet, see -> http://stackoverflow.com/questions/38338781/golang-access-raw-podio-field-values

Maybe the solution is that I do not let podio-go parse the values, but receive the raw json and start again from there?

As usual: your help is very much appreciated :)!

**Comment by andreas** [comment]
Hi 😄 

Because `field.Values` can be multiple types, it's currently typed as `interface{}` (i.e. it can be anything). To actually retrieve the values, you need to do a type coercion to one of the specific item values types, e.g. `[]TextValue{}`, `[]NumberValue{}`, etc.

Coercing `field.Values` safely can be done with a switch on `field.Type` using [the mapping from the README](https://github.com/andreas/podio-go#item-field-values), or a type switch on `field.Values`:

```go
// Example 1: Using field.Type to determine the type of field.Values
switch field.Type {
case "app":
  for _, appVal := range field.Values.([]AppValue) {
    fmt.Println(appVal.Value.AppItemId)
  }
case "date":
  // etc
}

// Example 2: Doing type coercion directly on field.Values
switch values := field.Values {
case []AppValue:
    for _, appVal := range values {
        fmt.Println(values[0].Value.AppItemId)
    }
case []DateValue:
  // etc
}
```

I hope the above helps.

**Comment by pjmuller** [comment]
Hi Andreas,

thanks for the quick response :) (as usual).

example 1 gives me this (runtime error, code does compile)

    error: interface conversion: interface is []interface {}, not []podio.AppValue

example 2 gives a compile error

    values := field.Values used as value
    cannot range over values (type interface {})
    invalid operation: values[0] (type interface {} does not support indexing)

Almost there, I can feel it :)

(PS: could be very useful, once we have a working example to put this in the example / readme) as other developers will maybe also run into the same issue...

**Comment by pjmuller** [comment]
Hi Andreas,

maybe useful that I paste the whole code I'm trying to get up and running.

    func parseValues(item *podio.Item) {
        for _, field := range item.Fields {
          // Example 1
          switch field.Type {
          case "app":
            for _, appVal := range field.Values.([]podio.AppValue) {
              fmt.Println(appVal.Value.AppItemId)
            }
          case "date":
            // etc
          }

          // Example 2
          switch values := field.Values {
          case []podio.AppValue:
              for _, appVal := range values {
                   fmt.Println(values[0].Value.AppItemId)
               }
           case []podio.DateValue:
             // etc
           }
    }

Probably it's just one small things that I'm doing wrong. Please help me out...

**Comment by andreas** [comment]
The following code works for me: https://gist.github.com/andreas/94edca19275f7ba49e426981eb620a83#file-example-go-L56-L70

There was indeed a small mistake in the code in the README for example 2:

```go
switch values := field.Values {
```

should be

```go
switch values := field.Values.(type) {
```

In hope the above helps.

**Comment by pjmuller** [comment]
Hi Andreas,

I copied your gist and ran this code -> https://gist.github.com/pjmuller/60f062d4e2a082c9f0f2a2b9a3578e48 (. It compiles but

- the first example still gives the error `interface conversion: interface is []interface {}, not []podio.AppValue`
- the second example never matches. so I always see "Field ....: Not app field type", even though there are app field types in that app

Strange that it is not working here...

**Comment by andreas** [comment]
Ok, I can replicate your problem now. I have tried to provide a quickfix in this branch: https://github.com/andreas/podio-go/tree/field-value-unmarshalling

Does that solve your issue?

**Comment by pjmuller** [comment]
Hi Andreas,

yes it seemed to solve the problem. GREAT :)!

One small issue I'm bumping into, the app values do not seem to continue any value. I'm always getting `[]` (even when there is an app reference). Have you also already noticed this behavior?

However other fields like category and text do give their actual content

**Comment by andreas** [comment]
Glad it works better -- there was a typo in the code for app values which caused the bug you noticed. It's fixed now in the same branch. Thanks for your patience :)

**Comment by pjmuller** [comment]
Thank you for your help :)!

As we both know the current item parser is still a bit limited (for example calculation field parsing, etc etc). In return for all your super quick help you'll see some pull requests coming. It might take some time, but it will come :)!

**Comment by stengaard** [comment]
Hi guys,

Was just struggling with this exact thing, so I filed #18 

Has behaviour changed in `json.Unmarshal` over the last few releases of Go? I assume the old (simpler) way has worked before? Anyway - a merge of #18 or @andreas's tree would be awesome.

Cheers!

**Comment by andreas** [comment]
@stengaard: Merged `field-value-unmarshalling` into `master` now. Sorry for wasted time 😞

**Comment by stengaard** [comment]
It's fine. At least there's a solution now! :)
