### ISSUE TITLE
How to return json directly

### ISSUE THREAD

**Issue by pjmuller** [andreas/podio-go#14]
Hi Andreas,

I have a new usecase where I would want golang to spit out the json directly WITHOUT parsing it into go interfaces.

Looking at the `client.go` file I tried something like

```

func (client *Client) Request(method string, path string, headers map[string]string, body io.Reader, out interface{}) error {
   	// ...
   	if out != nil {
		return json.Unmarshal(respBody, out)
	} else {
		return respBody
	}
```

But then I get the error that `[]byte does not implement error (missing Error method)` . I already tried converting in 10 different ways but I'm missing the magic one liner I believe.

So Question 1: Could you help me provide the one liner

Question 2: could I then create a PR for the `client.go`? Or how would you incorporate this behavior as you might want to keep returning nil whenever `out == nil`

**Comment by andreas** [comment]
Hi @pjmuller,

You can pass in a `json.RawMessage` as the `out` argument to `client.Request`:

```go
var rawResponse json.RawMessage
err := client.Request("GET", "/user", nil, nil, &rawResponse)
```

Hope it helps 😄

**Comment by pjmuller** [comment]
That was the magic online I was looking for. Works like a charm. Thanks :)!
