### ISSUE TITLE
Task parsing

### ISSUE THREAD

**Issue by pjmuller** [andreas/podio-go#16]
Hi Andreas,

sorry to post this always as issues, but it seems like a very direct channel to your genius go brain :). So here we go again.

I'm about to add API call for the https://developers.podio.com/doc/tasks/get-tasks-77949 API call.
However with this code

```
// https://developers.podio.com/doc/tasks/get-tasks-77949
func (client *Client) GetTasksJson(params map[string]interface{}) (rawResponse *json.RawMessage, err error) {
	err = client.RequestWithParams("GET", "/task/", nil, params, &rawResponse)
	return
}
```

I'm always getting `Error executing API Query not restrictive enough, must filter on either org, space, app, responsible, reference, created_by or completed_by`

Meaning that my params are not being passed. For the record, when I `fmt.Println` the params I get `map[space:123123123 sort_by:created_on limit:150 offset:0]` so there is a value.

Maybe something with the `RequestWithParams` that cannot handle [GET] + params requests well? I've not seen another example in the other files so there was no 'borrowing' to do this time.

Please assist :).

Greetings,
PJ

PS: And I know in order to do a PR I'll have to make a Task type etc, this will be done once I get the general stuff going

**Comment by andreas** [comment]
Hi PJ :)

You're right about the combination of `GET` and `params` being the issue: that Podio endpoint expects parameters to be passed as query parameters, not as the HTTP body. The current implementation of `RequestWithParams` JSON encodes the argument `params` and uses that as the body.

I have two ideas on how to solve this issue:

1) You can encode and add `params` as query parameters in `GetTasksJson`:

```go
// https://developers.podio.com/doc/tasks/get-tasks-77949
func (client *Client) GetTasksJson(params map[string]interface{}) (rawResponse *json.RawMessage, err error) {
    path := fmt.Sprintf("/task/?%s", urlEncodeParams(params))
    err = client.Request("GET", path, nil, nil, &rawResponse)
    return
}

func urlEncodeParams(params map[string]interface{}) string {
	values := url.Values{}
	for key, value := range params {
		values.Add(key, fmt.Sprint(value))
	}
	return values.Encode()
}
```

2) An alternative would be to try to make `RequestWithParams` smarter about how to encode the params, in which case your code for `GetTasksJson` should work as-is:

```go
func (client *Client) RequestWithParams(method string, path string, headers map[string]string, params map[string]interface{}, out interface{}) error {
	var body io.Reader

	if method == "GET" {
		pathURL, err := url.Parse(path)
		if err != nil {
			return err
		}
		query := pathURL.Query()
		for key, value := range params {
			query.Add(key, fmt.Sprint(value))
		}
		pathURL.RawQuery = query.Encode()
		path = pathURL.String()
	} else {
		buf, err := json.Marshal(params)
		if err != nil {
			return err
		}
		body = bytes.NewReader(buf)
	}

	return client.Request(method, path, headers, body, out)
}
```

I've tested the above code briefly, but no guarantees :)

**Comment by pjmuller** [comment]
Thanks for giving a thorough fix, so I went for approach 2.

On the same flow I created https://github.com/andreas/podio-go/pull/17 so that other can benefit from your efforts ;)
