### ISSUE TITLE
Item.Values parsing

### ISSUE THREAD

**Issue by msiebuhr** [andreas/podio-go#5]
Currently parsing of `Item.Field{...}` decodes apps to a generic `map[string]interface{}` instead of `App`, and date-fields become `[]*Value{nil}`.

I've hacked it for now using the following code:

    func (f *Field) UnmarshalJSON(data []byte) error {
        var fake struct {
                FieldId    float64  `json:"field_id"`
                ExternalId string   `json:"external_id"`
                Type       string   `json:"type"`
                Label      string   `json:"label"`
                Values     []*Value `json:"values"`
        }

        // Unmarshal regularly
        err := json.Unmarshal(data, &fake)
        if err != nil {
                return err
        }

        f.FieldId = fake.FieldId
        f.ExternalId = fake.ExternalId
        f.Type = fake.Type
        f.Label = fake.Label
        f.Values = fake.Values

        // Does it have a 'type'-key, so we can deduce anything about the values?
        switch f.Type {
        case "date":
                // Re-decode, as dates aren't wrapped in a 'values: [{value: ... }]', but 'values: [{...}]'
                var fakeValues struct {
                        Values []struct {
                                Start Time `json:"start"`
                        } `json:"values"`
                }

                err := json.Unmarshal(data, &fakeValues)
                if err != nil {
                        return err
                }

                f.Values = []*Value{}

                // Opimistically convert to date
                for _, val := range fakeValues.Values {
                        f.Values = append(f.Values, &Value{Value: val.Start})
                }

        case "app":
                // Hack: Re-encode to JSON and decode as an App
                for i, value := range f.Values {
                        reencodedValue, err := json.Marshal(value.Value)
                        if err != nil {
                                return err
                        }
                        var newItem Item
                        err = json.Unmarshal(reencodedValue, &newItem)
                        if err != nil {
                                return err
                        }
                        f.Values[i].Value = newItem
                }
        default:
        }

        return nil
    }

(It has a rather unfortunate side-effect that it internally decodes numbers to `float64` (`1.23456789e+09`), which it won't decode into `uint`'s, so all the `uint`'s in various places in the code was changed to `float64`'s.)

**Comment by andreas** [comment]
Thanks for raising this issue. The decoding of item values is indeed not very sophisticated. I have a couple of solutions in mind, but I'll need to prototype them to see what works in practice. :)

**Comment by msiebuhr** [comment]
Right.

Also - this doesn't maintain full fidelity (it only cares about `start`) and the re-marshalled data differs vastly from the ingested (i.e. Dates are now packed "correctly").

**Comment by andreas** [comment]
@msiebuhr please have a look at #7 and see if that helps :)
